// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/culture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/culture">> = Specific
  const handler = {} as typeof import("../../src/app/culture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/[tripId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[tripId]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/[tripId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/esim-usa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/esim-usa">> = Specific
  const handler = {} as typeof import("../../src/app/esim-usa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fourth-of-july/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fourth-of-july">> = Specific
  const handler = {} as typeof import("../../src/app/fourth-of-july/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/itinerary/[tripId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/itinerary/[tripId]">> = Specific
  const handler = {} as typeof import("../../src/app/itinerary/[tripId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/map">> = Specific
  const handler = {} as typeof import("../../src/app/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nightlife/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nightlife">> = Specific
  const handler = {} as typeof import("../../src/app/nightlife/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/photo-spots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/photo-spots">> = Specific
  const handler = {} as typeof import("../../src/app/photo-spots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planner">> = Specific
  const handler = {} as typeof import("../../src/app/planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/restaurants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/restaurants">> = Specific
  const handler = {} as typeof import("../../src/app/restaurants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/route-planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/route-planner">> = Specific
  const handler = {} as typeof import("../../src/app/route-planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sail4th-elcano/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sail4th-elcano">> = Specific
  const handler = {} as typeof import("../../src/app/sail4th-elcano/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shopping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shopping">> = Specific
  const handler = {} as typeof import("../../src/app/shopping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/viewpoints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/viewpoints">> = Specific
  const handler = {} as typeof import("../../src/app/viewpoints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/world-cup-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/world-cup-2026">> = Specific
  const handler = {} as typeof import("../../src/app/world-cup-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/location/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/location/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/location/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/hero-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/hero-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/hero-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trips/[tripId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips/[tripId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/trips/[tripId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/trips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trips">> = Specific
  const handler = {} as typeof import("../../src/app/api/trips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
