var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/onboarding/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bh3t3f._.js")
R.c("server/chunks/ssr/0r9g_next_dist_032~47d._.js")
R.c("server/chunks/ssr/0r9g_next_dist_esm_build_templates_app-page_12lkz30.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p94ha6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k2xhz7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__083l1pp._.js")
R.c("server/chunks/ssr/frontend_0bwv1z6._.js")
R.c("server/chunks/ssr/frontend_src_app_loading_tsx_0dopb3j._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_02pzh0k._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_forbidden_0hywuao.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_unauthorized_059~5ae.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_global-error_06bh~5g.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_onboarding_page_actions_03ono3y.js")
R.m(35054)
module.exports=R.m(35054).exports
