var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__05q7um4._.js")
R.c("server/chunks/ssr/0r9g_next_dist_032~47d._.js")
R.c("server/chunks/ssr/0r9g_next_dist_esm_build_templates_app-page_0783zgy.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p94ha6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k2xhz7._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_global-error_06bh~5g.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app__global-error_page_actions_08xoqom.js")
R.m(62894)
module.exports=R.m(62894).exports
