var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/[tripId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0an_8g5._.js")
R.c("server/chunks/ssr/0r9g_next_dist_032~47d._.js")
R.c("server/chunks/ssr/0r9g_next_dist_esm_build_templates_app-page_0d7fxx2.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p94ha6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k2xhz7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mjggqe._.js")
R.c("server/chunks/ssr/frontend_0bwv1z6._.js")
R.c("server/chunks/ssr/frontend_src_app_loading_tsx_0dopb3j._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_02pzh0k._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_forbidden_0hywuao.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_unauthorized_059~5ae.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_global-error_06bh~5g.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_dashboard_[tripId]_page_actions_0eg-xit.js")
R.m(87904)
module.exports=R.m(87904).exports
