// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/culture" | "/dashboard/[tripId]" | "/esim-usa" | "/fourth-of-july" | "/itinerary/[tripId]" | "/map" | "/nightlife" | "/onboarding" | "/photo-spots" | "/planner" | "/profile" | "/restaurants" | "/route-planner" | "/sail4th-elcano" | "/settings" | "/shopping" | "/viewpoints" | "/world-cup-2026"
type AppRouteHandlerRoutes = "/api/location/search" | "/api/media/hero-image" | "/api/trips" | "/api/trips/[tripId]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/location/search": {}
  "/api/media/hero-image": {}
  "/api/trips": {}
  "/api/trips/[tripId]": { "tripId": string; }
  "/culture": {}
  "/dashboard/[tripId]": { "tripId": string; }
  "/esim-usa": {}
  "/fourth-of-july": {}
  "/itinerary/[tripId]": { "tripId": string; }
  "/map": {}
  "/nightlife": {}
  "/onboarding": {}
  "/photo-spots": {}
  "/planner": {}
  "/profile": {}
  "/restaurants": {}
  "/route-planner": {}
  "/sail4th-elcano": {}
  "/settings": {}
  "/shopping": {}
  "/viewpoints": {}
  "/world-cup-2026": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
