var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/nightlife/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g4hefe._.js")
R.c("server/chunks/ssr/frontend_src_00-4wj1._.js")
R.c("server/chunks/ssr/0r9g_next_dist_esm_build_templates_app-page_09dy-o4.js")
R.c("server/chunks/ssr/0r9g_next_dist_032~47d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p94ha6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k2xhz7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mjggqe._.js")
R.c("server/chunks/ssr/frontend_0bwv1z6._.js")
R.c("server/chunks/ssr/frontend_src_app_loading_tsx_0dopb3j._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_02pzh0k._.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_forbidden_0hywuao.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_unauthorized_059~5ae.js")
R.c("server/chunks/ssr/0r9g_next_dist_client_components_builtin_global-error_06bh~5g.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_nightlife_page_actions_0cz8d3z.js")
R.m(84893)
module.exports=R.m(84893).exports
